name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build-python-wheels:
    name: Build cp310 wheels (Linux + Windows)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
        arch: [auto64]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.1
        with:
          package-dir: python
          output-dir: python/wheelhouse
        env:
          # build only Python 3.10 wheels
          CIBW_BUILD: cp310-*

          # skip unwanted platforms
          CIBW_SKIP: aarch64 *-musllinux_* pp* macos-*

          # environment setup
          CIBW_ENVIRONMENT_PASS_LINUX: CIBW_ARCHS
          CIBW_ENVIRONMENT_WINDOWS: CTRANSLATE2_ROOT='${{ github.workspace }}\install'
          CIBW_BEFORE_ALL_LINUX: python/tools/prepare_build_environment_linux.sh
          CIBW_BEFORE_ALL_WINDOWS: bash python/tools/prepare_build_environment_windows.sh
          CIBW_BEFORE_BUILD: pip install -r python/install_requirements.txt

          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_ARCHS: ${{ matrix.arch }}

      - name: Upload Python wheels
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ runner.os }}-${{ matrix.arch }}
          path: python/wheelhouse

  test-python-wheels:
    needs: [build-python-wheels]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.11"

      - uses: actions/checkout@v4

      - name: Prepare test environment
        shell: bash
        run: ./python/tools/prepare_test_environment.sh

      - name: Download Python wheels
        uses: actions/download-artifact@v4
        with:
          pattern: python-wheels-${{ runner.os }}-*
          merge-multiple: true
          path: .

      - name: Install wheel (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: pip install *cp310*manylinux*x86_64.whl

      - name: Install wheel (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: bash
        run: pip install *cp310*win*.whl

      - name: Run tests
        shell: bash
        run: pytest -v python/tests/ --ignore=python/tests/test_opennmt_tf.py

  check-python-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.11"

      - name: Install dependencies
        run: python -m pip install black==22.* flake8==3.8.* isort==5.*

      - name: Check code format with Black
        working-directory: python
        run: black --check .

      - name: Check imports order with isort
        working-directory: python
        run: isort --check-only .

      - name: Check code style with Flake8
        working-directory: python
        run: flake8 .

  publish-python-wheels-on-pypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [build-python-wheels, test-python-wheels, check-python-style]
    runs-on: ubuntu-22.04

    steps:
      - name: Download Python wheels
        uses: actions/download-artifact@v4
        with:
          pattern: python-wheels-*
          merge-multiple: true
          path: .

      - name: Publish Python wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: .
